name: Deploy DevOps Demo App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Install Trivy on the runner
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          sudo mv ./bin/trivy /usr/local/bin/trivy
          trivy --version

      # Step 3: Pull Docker image locally on runner and scan
      - name: Scan Docker image with Trivy
        run: |
          docker pull waeltoukebri/devops-demo-app:latest || echo "Vulnerabilities found"
          trivy image --severity HIGH,CRITICAL waeltoukebri/devops-demo-app:latest

      # Step 4: Deploy Docker container on EC2
      - name: Deploy Docker on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Stop & remove old container
            docker stop devops-demo || true
            docker rm devops-demo || true

            # Pull latest image
            docker pull waeltoukebri/devops-demo-app:latest

            # Run container with health check
            docker run -d \
              -p 80:80 \
              --name devops-demo \
              --restart unless-stopped \
              --health-cmd="curl -f http://localhost/ || exit 1" \
              --health-interval=30s \
              --health-retries=3 \
              waeltoukebri/devops-demo-app:latest

            # Show running containers and health status
            docker ps
            docker inspect --format='{{.Name}} {{.State.Health.Status}}' devops-demo

          # Create a network so containers can talk to each other
            docker network create monitoring-network || true

            # Run Node Exporter (The Metrics Source)
            docker stop node-exporter || true && docker rm node-exporter || true
            docker run -d --name node-exporter --network monitoring-network -p 9100:9100 prom/node-exporter

            # Run Prometheus (The Data Collector)
            docker stop prometheus || true && docker rm prometheus || true
            docker run -d --name prometheus --network monitoring-network -p 9090:9090 \
              -v /home/ec2-user/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml \
              prom/prometheus

            # Run Grafana (The Visualization)
            docker stop grafana || true && docker rm grafana || true
            docker run -d --name grafana --network monitoring-network -p 3000:3000 grafana/grafana
